search_tweets_api:
  bearer_token: AAAAAAAAAAAAAAAAAAAAAFqVRAEAAAAAVhgVrMRAHmAWkj6VKiXD1rnI3zo%3Dx5ATTi9yI7F2TPnhOgrEg3cMeQpPSVNbsUHtR3fKMNJz9iU6bm
azure:
  subscription_key: b0c08ff8e4944cb98aee1be362f06a9d